INSERT INTO regions (id, name, country_id)
VALUES (1, 'Dar-es-salaam', 1),
       (2, 'Tanga', 1),
       (3, 'Arusha', 1),
       (4, 'Kilimanjaro', 1),
       (5, 'Manyara', 1),
       (6, 'Geita', 1),
       (7, 'Mara', 1),
       (8, 'Mwanza', 1),
       (9, 'Kagera', 1),
       (10, 'Shinyanga', 1),
       (11, 'Simiyu', 1),
       (12, 'Dodoma', 1),
       (13, 'Singida', 1),
       (14, 'Tabora', 1),
       (15, 'Kigoma', 1),
       (16, 'Katavi', 1),
       (17, 'Iringa', 1),
       (18, 'Mbeya', 1),
       (19, 'Songwe', 1),
       (20, 'Rukwa', 1),
       (21, 'Ruvuma', 1),
       (22, 'Njombe', 1),
       (23, 'Pwani', 1),
       (24, 'Mtwara', 1),
       (25, 'Lindi', 1),
       (26, 'Morogoro', 1),
       (27, 'Mjini Magharibi', 1),
       (28, 'Kusini Unguja', 1),
       (29, 'Kaskazini Unguja', 1),
       (30, 'Kusini Pemba', 1),
       (31, 'Kaskazini Pemba', 1);
